## The name of this GitHub Action:
name: "Build DECAF Clever Runtime on Pull Requests"

## When will this GitHub Action run?
on:
  ## This GitHub Action will run for every event on a PR including pushes:
  pull_request:

  ## TODO: Separate somewhere else below after testing.
  ## This GitHub Action will run for every tag push:
  push:
    ## Include all tags including hierarchical tags such as v1.0.0/beta
    tags:
      - '**'

## Which GitHub permissions are required?
##
## NOTE: Currently, we do not make use of these permissions.
permissions:
  contents: write
  pull-requests: write

## Jobs to run in this GitHub Action:
jobs:
  ## Build the Docker image:
  build-and-push-docker-image:
    ## GitHub-hosted runner that we are we going to run this job on:
    runs-on: ubuntu-22.04

    env:
      DOCKER_REGISTRY: "${{ secrets.DECAF_DOCKER_REGISTRY }}"
      DOCKER_REGISTRY_USERNAME: "${{ secrets.DECAF_DOCKER_REGISTRY_USERNAME }}"
      DOCKER_REGISTRY_PASSWORD: "${{ secrets.DECAF_DOCKER_REGISTRY_PASSWORD }}"
      DOCKER_IMAGE_REPOSITORY: "decaf-clever-runtime-remaputils"
      #DOCKER_IMAGE_TAG: "pr-${{ github.event.pull_request.number }}test"
      DOCKER_IMAGE_TAG: "${{ github.ref_name }}"

    ## Steps of this job:
    steps:
      ## Checkout the codebase:
      - name: Checkout
        uses: actions/checkout@v3

      ## Setup Docker Buildx:
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2

      ## Login to Docker Registry:
      - name: "Login to Docker Registry"
        uses: docker/login-action@v2
        with:
          registry: "${{ env.DOCKER_REGISTRY }}"
          username: "${{ env.DOCKER_REGISTRY_USERNAME }}"
          password: "${{ env.DOCKER_REGISTRY_PASSWORD }}"

      ## Build and push the Docker image:
      - name: "Build and Push Docker Image"
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          ## TODO: Enable below  after testing.
          # push: true
          context: .
          build-args: |
            VERSION=${{ env.DOCKER_IMAGE_TAG }}
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_REPOSITORY }}:${{ env.DOCKER_IMAGE_TAG }}
